module_order:
    - fastqc:
        name: 'FastQC (raw)'
        info: 'This section of the report shows FastQC results before adapter trimming.'
        path_filters:
            - './fastqc/*.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        path_filters:
            - './trimgalore/fastqc/*.zip'

extra_fn_clean_exts:
    - '_val_2'
    - '_val_1'

custom_data:
    checkm:
        file_format: "tsv"
        section_name: "CheckM"
        description: "Genome completeness and contamination estimation."
        plot_type: "table"
        pconfig:
            id: 'checkm_stats'
            namespace: 'Genome QC stats'
        headers:
            Bin Id:
                description: 'Sample'
            Marker lineage:
                description: 'Lineage used to estimate completeness'
            Completeness:
                description: 'Estimated genome completeness'
                format: '{:,.2f}'
            Contamination:
                description: 'Estimated genome contamination'
                format: '{:,.2f}'
            Strain heterogeneity:
                description: 'Estimated strain heterogeneity'
                format: '{:,.2f}'

sp:
    cutadapt:
        fn: '*trimming_report.txt'
    checkm:
        fn: 'checkm_*.tsv'
